<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderLinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    

        $data = [
            [
                "id" => 1, 
                "order_id" => 1, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC85HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 2, 
                "order_id" => 1, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC86HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 3, 
                "order_id" => 1, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC87HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 4, 
                "order_id" => 2, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC88HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 5, 
                "order_id" => 2, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC89HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 6, 
                "order_id" => 3, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC91HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 7, 
                "order_id" => 3, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC92HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 8, 
                "order_id" => 4, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC93HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 9, 
                "order_id" => 4, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC94HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 10, 
                "order_id" => 4, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC95HG', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 11, 
                "order_id" => 5, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC96HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 12, 
                "order_id" => 5, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC97HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 13, 
                "order_id" => 6, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC98HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 14, 
                "order_id" => 6, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC99HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 15, 
                "order_id" => 7, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC87HG7', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
         
            //INTERNAL TESTING
            //  [
            //     "id" => 1, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC62HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 2, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC63HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 3, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC64HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 4, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC65HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 5, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC66HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 7, 
            //     "order_id" => 3, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC68HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 8, 
            //     "order_id" => 3, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC69HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 9, 
            //     "order_id" => 4, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC70HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 10, 
            //     "order_id" => 4, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC71HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 11, 
            //     "order_id" => 4, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC72HG', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 12, 
            //     "order_id" => 5, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC73HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 13, 
            //     "order_id" => 5, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC74HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 14, 
            //     "order_id" => 6, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC75HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 15, 
            //     "order_id" => 6, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC76HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 16, 
            //     "order_id" => 7, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC64HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
        ];
        

        foreach ($data as $orderLine) {
            DB::table('list_of_order_lines')->updateOrInsert(['id' => $orderLine['id']], $orderLine);
        }
    }
}
