<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderLinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            // [
            //     "id" => 1, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC01HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 2, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC02HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 3, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC03HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 4, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC04HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 5, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC05HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 6, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC07HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 7, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC08HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 8, 
            //     "order_id" => 1, 
            //     "dep_company_id" => 10000, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC09HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 9, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC10HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 10, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC11HG', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 11, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC12HG', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 12, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC13HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 13, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC14HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
            // [
            //     "id" => 14, 
            //     "order_id" => 2, 
            //     "dep_company_id" => 10002, 
            //     "digits_code" => '90003217', 
            //     "item_description" => 'IPHONE 7', 
            //     "brand" => 'APPLE', 
            //     "wh_category" => 'APPLE', 
            //     "quantity" => '1', 
            //     "serial_number" => 'C8HXFC15HG7F', 
            //     "enrollment_status_id" => 1, 
            //     "created_at" => now(), 
            //     "updated_at" => now()
            // ],
         
            //INTERNAL TESTING
             [
                "id" => 1, 
                "order_id" => 1, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC17HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 2, 
                "order_id" => 1, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC18HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 3, 
                "order_id" => 1, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC19HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 4, 
                "order_id" => 2, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC20HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 5, 
                "order_id" => 2, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC21HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 6, 
                "order_id" => 3, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC22HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 7, 
                "order_id" => 4, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC23HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 8, 
                "order_id" => 4, 
                "dep_company_id" => 10000, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC24HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 9, 
                "order_id" => 5, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC25HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 10, 
                "order_id" => 5, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC26HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 11, 
                "order_id" => 5, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC27HG', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 12, 
                "order_id" => 6, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC28HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 13, 
                "order_id" => 6, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC29HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 14, 
                "order_id" => 7, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC30HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
            [
                "id" => 14, 
                "order_id" => 7, 
                "dep_company_id" => 10002, 
                "digits_code" => '90003217', 
                "item_description" => 'IPHONE 7', 
                "brand" => 'APPLE', 
                "wh_category" => 'APPLE', 
                "quantity" => '1', 
                "serial_number" => 'C8HXFC31HG7F', 
                "enrollment_status_id" => 1, 
                "created_at" => now(), 
                "updated_at" => now()
            ],
        ];
        

        foreach ($data as $orderLine) {
            DB::table('list_of_order_lines')->updateOrInsert(['id' => $orderLine['id']], $orderLine);
        }
    }
}
