<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderLinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
               "id" => 1, 
               "order_id" => 1, 
               "dep_company_id" => 570, 
               "digits_code" => '90003217', 
               "item_description" => 'APP DEM IPHONE 7P 32GB BLACK', 
               "brand" => 'APPLE', 
               "wh_category" => 'APPLE', 
               "quantity" => '1', 
               "serial_number" => 'C2YH2DYAHG7F', 
               "enrollment_status_id" => 1, 
               "created_at" => now(), 
               "updated_at" => now()
            ],
            [
                'id' => 2,
                'order_id' => 1,
                'dep_company_id' => 570,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYBHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'order_id' => 1,
                'dep_company_id' => 570,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYCHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'order_id' => 1,
                'dep_company_id' => 570,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYDHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'order_id' => 1,
                'dep_company_id' => 570,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYEHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'order_id' => 2,
                'dep_company_id' => 568,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYFHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'order_id' => 2,
                'dep_company_id' => 568,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYGHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'order_id' => 2,
                'dep_company_id' => 568,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYHHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'order_id' => 2,
                'dep_company_id' => 568,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYJHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'order_id' => 2,
                'dep_company_id' => 568,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYKHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'order_id' => 3,
                'dep_company_id' => 2,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYLHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'order_id' => 3,
                'dep_company_id' => 3,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYMHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'order_id' => 3,
                'dep_company_id' => 538,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYNHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'order_id' => 3,
                'dep_company_id' => 538,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYPHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'order_id' => 3,
                'dep_company_id' => 538,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYQHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'order_id' => 4,
                'dep_company_id' => 571,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYRHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'order_id' => 4,
                'dep_company_id' => 571,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYSHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'order_id' => 4,
                'dep_company_id' => 571,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYTHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'order_id' => 4,
                'dep_company_id' => 2,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYUHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'order_id' => 4,
                'dep_company_id' => 13,
                'digits_code' => '90003217',
                'item_description' => 'APP DEM IPHONE 7P 32GB BLACK',
                'brand' => 'APPLE',
                'wh_category' => 'APPLE',
                'quantity' => '1',
                'serial_number' => 'C2YH2DYVHG7F',
                'enrollment_status_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        
            
        
        ];

        foreach ($data as $orderLine) {
            DB::table('list_of_order_lines')->updateOrInsert(['id' => $orderLine['id']], $orderLine);
        }
    }
}
